### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by davelab6** [elliotkendall/pdf2slides#1]
Is this available under Apache license? :)

**Comment by elliotkendall** [comment]
Guess I didn't pick a license, huh?

I tend to release all my code under GPLv3. I'm happy to explicitly add that license if it'll help you.

**Comment by davelab6** [comment]
GPLv3 would be great! I asked @roeln to take a look as I couldn't get it working

**Comment by elliotkendall** [comment]
Done. Uploaded GPL3 as LICENSE
